"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Pessoa_1 = require("./Pessoa");
const Cliente_1 = require("./Cliente");
const Empregado_1 = require("./Empregado");
let pessoa1 = new Pessoa_1.Pessoa("Raphael anizio", 27, "SP", "São Paulo", "1246978452-45");
pessoa1.apresentar();
let pessoa2 = new Pessoa_1.Pessoa("Nildin vieira", 30, "SP", "São Paulo", "236789453-65-45");
pessoa2.apresentar();
let cliente1 = new Cliente_1.Cliente("Anderson alves", 28, "SP", "Santo Andre", true, "14532199965");
cliente1.apresentar();
cliente1.verAssinatura();
let cliente2 = new Cliente_1.Cliente("Ingrid Sousa", 23, "SP", "Guarulhos", false, "14532199965");
cliente2.apresentar();
cliente2.verAssinatura();
cliente2.getCpf();
let empregado = new Empregado_1.Empregado("João Paulo", 25, "Salvador", "Bahia", "123456789");
empregado.apresentar();
empregado.contrato();
